"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

[directory]
home_symbol = "ðŸ "
truncation_length = 4
style = "bold lavender"
truncation_symbol = "â€¦/"

[package]
disabled = true

[[battery.display]]
threshold = 50

# jj config yoinked from https://github.com/dpetersen/dotfiles/blob/c8a9ae1424b6d5fcefcedd646c094d40936b8b03/home/dot_config/starship.toml

[custom.jj]
description = "The current jj status"
when = "jj --ignore-working-copy root"
shell = ["bash", "--norc", "--noprofile"]
symbol = "ðŸ¥‹ "
command = '''
jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
  separate(" ",
    change_id.shortest(8),
    bookmarks,
    "|",
    concat(
      if(conflict, "ðŸ’¥"),
      if(divergent, "ðŸš§"),
      if(hidden, "ðŸ‘»"),
      if(immutable, "ðŸ”’"),
      if(empty, "ðŸ“­", "ðŸ“¬"),
    ),
    concat(
      if(empty || description.len() > 0, raw_escape_sequence("\x1b[1;32m"), raw_escape_sequence("\x1b[1;33m")),
      coalesce(
        description.first_line(),
        "(no description set)",
      ),
      raw_escape_sequence("\x1b[0m")
    ),
  )
'
'''

[git_status]
disabled = true
[git_commit]
disabled = true
[git_metrics]
disabled = true
[git_branch]
disabled = true