[[language]]
name = "java"
language-servers = [ "jdtls", "cspell" ]

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "cspell" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "cspell" ]

[[language]]
name = "python"
language-servers = [ "ruff", "cspell" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "cspell" ]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.cspell]
command = "cspell-lsp"
args = ["--stdio"]
